<?php

namespace Database\Seeders;

use App\Models\Disease;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $diseases = [
            ['Akar (Blast Disease)', '<div>Penyakit akar kelapa sawit, atau sering disebut blast disease, merupakan masalah serius yang dapat mengakibatkan kerugian besar dalam produksi kelapa sawit. Berikut beberapa solusi untuk mengatasi penyakit ini:<br><br><strong>1. Identifikasi Dini</strong></div><ul><li>Pantau secara rutin kebun kelapa sawit untuk mendeteksi gejala awal penyakit akar. Gejala yang umum termasuk daun menguning, layu, dan akhirnya mati.</li></ul><div><strong>2. Sanitasi dan Manajemen Lahan</strong></div><ul><li>Jaga kebersihan lahan dengan menghilangkan sisa-sisa tanaman yang terinfeksi dan gulma.</li><li>Buang dan bakar tanaman yang terinfeksi untuk mencegah penyebaran patogen.</li></ul><div><strong>3. Penggunaan Varietas Tahan</strong></div><ul><li>Pilih dan tanam varietas kelapa sawit yang memiliki ketahanan lebih baik terhadap penyakit akar.</li></ul><div><strong>4. Pengendalian Biologis</strong></div><ul><li>Gunakan agen biokontrol seperti Trichoderma harzianum yang dapat menghambat pertumbuhan patogen penyebab penyakit akar.</li></ul><div><strong>5. Pemupukan dan Pengairan yang Tepat</strong></div><ul><li>Pastikan tanaman mendapat nutrisi yang cukup dengan pemupukan yang seimbang.</li><li>Kelola sistem pengairan untuk menghindari kondisi yang terlalu lembab atau terlalu kering, karena keduanya dapat meningkatkan risiko infeksi.</li></ul><div><strong>6. Penggunaan Fungisida</strong></div><ul><li>Aplikasi fungisida sistemik yang sesuai dapat membantu mengendalikan penyakit. Namun, penggunaannya harus sesuai dengan petunjuk agar tidak menimbulkan resistensi.</li></ul><div><strong>7. Rotasi Tanaman</strong></div><ul><li>Lakukan rotasi tanaman dengan tanaman yang bukan inang patogen untuk mengurangi populasi patogen di dalam tanah.</li></ul><div><strong>8. Penanaman Jarak Tanam yang Tepat</strong></div><ul><li>Tanam kelapa sawit dengan jarak yang cukup untuk memungkinkan sirkulasi udara yang baik dan mengurangi kelembaban yang dapat mendukung pertumbuhan patogen.</li></ul><div>Pendekatan terpadu yang menggabungkan berbagai metode di atas akan memberikan hasil yang lebih efektif dalam mengendalikan penyakit akar kelapa sawit.</div>'],
            ['Busuk Pangkal Batang (Basal Stem Rot/Ganoderma)', '<div>Penyakit busuk pangkal batang kelapa sawit, seperti yang disebabkan oleh jamur Ganoderma, merupakan masalah serius dalam pertanian kelapa sawit. Beberapa solusi yang bisa dipertimbangkan untuk mengatasi penyakit ini antara lain:<br><br><strong>1. Penggunaan bibit unggul</strong></div><ul><li>Gunakan bibit kelapa sawit yang tahan terhadap penyakit Ganoderma jika tersedia.</li></ul><div><strong>2. Rotasi tanaman</strong></div><ul><li>Praktikkan rotasi tanaman dengan tanaman lain untuk mengurangi penyebaran penyakit di tanah.</li></ul><div><strong>3. Pengelolaan tanah</strong></div><ul><li>Pastikan drainase tanah baik untuk mengurangi kelembaban yang menyebabkan kondisi ideal bagi jamur Ganoderma.</li></ul><div><strong>4. Pengendalian gulma</strong></div><ul><li>Gulma dapat menjadi inang sementara bagi Ganoderma, jadi penting untuk mengendalikan pertumbuhannya.</li></ul><div><strong>5. Sanitasi</strong></div><ul><li>Buang sisa-sisa tanaman yang terinfeksi dengan benar untuk mencegah penyebaran penyakit.</li></ul><div><strong>6. Pemupukan seimbang</strong></div><ul><li>Pemupukan yang tepat dapat membantu meningkatkan ketahanan tanaman terhadap penyakit.</li></ul><div><strong>7. Penggunaan biofungisida</strong></div><ul><li>Beberapa penelitian telah menunjukkan bahwa penggunaan biofungisida tertentu dapat membantu mengendalikan infeksi Ganoderma.</li></ul><div><strong>8. Kerjasama dengan pakar</strong></div><ul><li>Konsultasikan dengan ahli pertanian atau peneliti yang berpengalaman dalam manajemen Ganoderma untuk strategi lebih lanjut.</li></ul><div>Setiap langkah ini perlu disesuaikan dengan kondisi lokal dan praktek pertanian yang sesuai. Menangani penyakit ini membutuhkan pendekatan holistik dan berkelanjutan untuk mengurangi dampaknya pada tanaman kelapa sawit.</div>'],
            ['Busuk Kuncup (Spear Rot)', '<div>Penyakit kelapa sawit seperti spear root bisa diatasi dengan beberapa langkah pengendalian penyakit yang efektif, antara lain:<br><br><strong>1. Sanitasi.</strong> Membersihkan dan membuang bagian tanaman yang terinfeksi secara teratur untuk mengurangi sumber penyebaran penyakit.<br><strong>2. Pemangkasan.</strong> Memangkas daun dan ranting yang terinfeksi untuk mengurangi penyebaran penyakit.<br><strong>3. Pemupukan dan Irigasi yang Tepat.</strong> Memastikan tanaman mendapatkan nutrisi yang cukup dan air yang cukup untuk meningkatkan daya tahan terhadap penyakit.<br><strong>4. Penggunaan Fungisida.</strong> Penggunaan fungisida yang direkomendasikan secara teratur untuk mengendalikan perkembangan penyakit.<br><strong>5. Rotasi Tanaman.</strong> Mempraktikkan rotasi tanaman untuk mengurangi penyebaran penyakit di lapangan.<br><strong>6. Pemantauan Rutin.</strong>&nbsp;Melakukan pemantauan rutin terhadap kondisi tanaman untuk deteksi dini penyakit dan tindakan pencegahan yang tepat waktu.<br><br>Langkah-langkah ini dapat membantu mengurangi dampak dari penyakit spear rot pada kelapa sawit.</div>'],
            ['Garis Kuning (Patch Yellow)', '<div>Penyakit garis kuning pada kelapa sawit disebabkan oleh virus yang menyebar melalui serangga pembawa. Berikut beberapa langkah yang dapat dilakukan untuk mengatasi penyakit ini:<br><br><strong>1. Pengendalian Serangga Pembawa Virus</strong></div><ul><li>Lindungi kelapa sawit dari serangga seperti kutu daun atau tungau yang dapat membawa virus. Gunakan insektisida yang direkomendasikan untuk mengurangi populasi serangga pembawa.</li></ul><div><strong>2. Pengelolaan Tanaman</strong></div><ul><li>Pastikan kelapa sawit mendapatkan nutrisi yang cukup dan kondisi tumbuh yang optimal. Tanaman yang sehat lebih tahan terhadap serangan penyakit.</li></ul><div><strong>3. Praktek Budidaya yang Baik</strong></div><ul><li>Praktek budidaya seperti sanitasi yang baik, pemangkasan yang tepat, dan manajemen gulma dapat membantu mengurangi keberadaan serangga pembawa dan penyebaran virus.</li></ul><div><strong>4. Kebersihan Area Perkebunan</strong></div><ul><li>Pastikan area perkebunan kelapa sawit tetap bersih dari sisa-sisa tanaman yang sakit atau mati yang dapat menjadi tempat hidup bagi serangga pembawa virus.</li></ul><div><strong>5. Pemantauan Rutin</strong></div><ul><li>Lakukan pemantauan rutin terhadap kondisi kelapa sawit untuk mendeteksi dini gejala penyakit garis kuning. Tindakan dini dapat membantu mengendalikan penyebaran penyakit.</li></ul><div>Memadukan berbagai strategi ini dapat membantu mengurangi risiko dan dampak penyakit garis kuning pada kelapa sawit.</div>'],
            ['Tajuk (Crown Disease)', '<div>Penyakit tajuk pada kelapa sawit, yang juga dikenal sebagai penyakit mahkota, dapat diatasi dengan beberapa langkah pencegahan dan pengelolaan. Berikut beberapa solusi yang bisa dipertimbangkan:<br><br><strong>1. Pemantauan Rutin.</strong> Lakukan pemantauan rutin terhadap kebun kelapa sawit untuk mendeteksi gejala penyakit sejak dini.<br><strong>2. Sanitasi Kebun.</strong> Pastikan kebun kelapa sawit bersih dari sisa-sisa tanaman yang terinfeksi atau pohon yang mati untuk mengurangi kemungkinan penyebaran penyakit.<br><strong>3. Pengelolaan Tanaman.</strong> Terapkan praktik-praktik budidaya yang baik, seperti pemupukan yang tepat dan irigasi yang memadai, untuk memperkuat pertahanan tanaman terhadap penyakit.<br><strong>4. Penggunaan Varietas Tahan.</strong> Pilih varietas kelapa sawit yang tahan terhadap penyakit tajuk jika memungkinkan.<br><strong>5. Pengendalian Hama dan Penyakit.</strong>&nbsp;Gunakan pengendalian hama dan penyakit secara terintegrasi, termasuk penggunaan fungisida atau pestisida jika diperlukan, sesuai dengan pedoman yang berlaku.<br><br>Memadukan berbagai strategi ini dapat membantu mengurangi risiko dan dampak penyakit tajuk pada kelapa sawit.</div>'],
            ['Busuk Tandan', '<div>Untuk mengatasi penyakit busuk tandan kelapa sawit, beberapa langkah yang dapat diambil meliputi:<br><br><strong>1. Pengendalian Hama dan Penyakit.</strong> Lakukan pengendalian hama dan penyakit secara teratur dengan menggunakan pestisida yang sesuai dan aman untuk lingkungan.<br><strong>2. Praktik Budidaya yang Baik.</strong> Terapkan praktik budidaya yang baik seperti rotasi tanaman, sanitasi kebun yang baik, dan penggunaan bibit yang sehat.<br><strong>3. Pemupukan yang Tepat.</strong> Pastikan pemupukan yang tepat untuk meningkatkan kekebalan tanaman terhadap penyakit.<br><strong>4. Pengaturan Drainase.</strong> Pastikan drainase kebun sawit baik untuk mengurangi kelembaban yang dapat memicu pertumbuhan penyakit.<br><strong>5. Pengawasan Rutin.</strong> Lakukan pengawasan rutin terhadap kebun sawit untuk mendeteksi gejala penyakit secara dini.<br><br>Tindakan ini dapat membantu mengurangi risiko dan dampak dari penyakit busuk tandan kelapa sawit.</div>']
        ];

        foreach ($diseases as $disease) {
            Disease::create([
                'uuid' => Str::uuid(),
                'nama' => $disease[0],
                'solusi' => $disease[1]
            ]);
        }
    }
}
